"""Integration tests — full games, cross-module."""

from __future__ import annotations


class TestIntegration:
    def test_growth_only(self) -> None: ...
    def test_blocking_and_combat(self) -> None: ...
    def test_crowding_kills_town(self) -> None: ...
    def test_viewer_replays_record(self) -> None: ...
    def test_bot_sees_delayed_world(self) -> None: ...
