"""Tests for the spatial hash grid."""

from __future__ import annotations


class TestSpatialHash:
    def test_same_cell_within_radius(self) -> None: ...
    def test_query_matches_brute(self) -> None: ...
    def test_rebuild_clears_old(self) -> None: ...
    def test_cell_size_invariant(self) -> None: ...
    def test_crowding_sum_vs_brute(self) -> None: ...
    def test_performance(self) -> None: ...
