"""Tests for determinism — identical inputs → identical outputs."""

from __future__ import annotations


class TestDeterminism:
    def test_identical_jsonl(self) -> None: ...
    def test_deterministic_with_bots(self) -> None: ...
    def test_float_stable(self) -> None: ...
    def test_no_random_imports(self) -> None: ...
    def test_turn_order_tiebreak(self) -> None: ...
