"""Tests for score computation — cross-cutting (uses engine/world + engine/config)."""

from __future__ import annotations


class TestScore:
    def test_formula(self) -> None: ...
    def test_only_alive_counted(self) -> None: ...
    def test_at_start(self) -> None: ...
    def test_empty_faction(self) -> None: ...
    def test_build_vs_score(self) -> None: ...
    def test_train_vs_score(self) -> None: ...
