"""Tests for runner/main — bot protocol, startup, timeout, end message."""

from __future__ import annotations


class TestBotProtocol:
    def test_startup_config(self) -> None: ...
    def test_startup_faction(self) -> None: ...
    def test_startup_go(self) -> None: ...
    def test_per_turn_header(self) -> None: ...
    def test_bot_response_parsed(self) -> None: ...
    def test_all_command_types(self) -> None: ...
    def test_timeout_kills(self) -> None: ...
    def test_timeout_permanence(self) -> None: ...
    def test_go_terminator_required(self) -> None: ...
    def test_incremental_updates(self) -> None: ...
    def test_end_message(self) -> None: ...
    def test_end_after_timeout(self) -> None: ...
    def test_malformed_line_ignored(self) -> None: ...
    def test_unknown_faction_ignored(self) -> None: ...
