"""Tests for engine/ledger — already moved from tests/test_ledger.py."""

from __future__ import annotations


class TestLedgerLogging:
    def test_log_event(self) -> None: ...
    def test_event_tuple_fields(self) -> None: ...
    def test_events_sorted_by_time(self) -> None: ...


class TestLedgerVisibility:
    def test_visible_within_delay(self) -> None: ...
    def test_not_yet_visible(self) -> None: ...
    def test_at_capital_zero_delay(self) -> None: ...
    def test_faction_specific(self) -> None: ...
    def test_no_delivery_during_flight(self) -> None: ...


class TestLedgerEviction:
    def test_evict_old_events(self) -> None: ...
    def test_window_size(self) -> None: ...
    def test_eviction_o1(self) -> None: ...
    def test_no_premature_eviction(self) -> None: ...
