"""Tests for engine/world — entities, map parsing, capital assignment."""

from __future__ import annotations


class TestMap:
    def test_csv_town(self) -> None: ...
    def test_csv_army(self) -> None: ...
    def test_faction_letters(self) -> None: ...
    def test_own_faction_relabelled(self) -> None: ...
    def test_capital_is_first_town(self) -> None: ...
    def test_capital_per_faction(self) -> None: ...
    def test_continuous_positions(self) -> None: ...
    def test_edge_clamping_move(self) -> None: ...
    def test_edge_clamping_spawn(self) -> None: ...
    def test_map_size_respected(self) -> None: ...
    def test_population_required_for_town(self) -> None: ...
    def test_army_population_ignored(self) -> None: ...


class TestEntities:
    def test_army_fields(self) -> None: ...
    def test_town_fields(self) -> None: ...
    def test_town_death_threshold(self) -> None: ...
    def test_town_ids_stable(self) -> None: ...
    def test_army_ids_unique(self) -> None: ...
