"""Tests for engine/step — turn resolution order, info delay, order lag, commands."""

from __future__ import annotations


class TestTurnOrder:
    def test_command_before_movement(self) -> None: ...
    def test_combat_after_movement(self) -> None: ...
    def test_economy_after_combat(self) -> None: ...
    def test_knowledge_after_economy(self) -> None: ...
    def test_fresh_spawns_immune_this_turn(self) -> None: ...
    def test_eviction_last(self) -> None: ...
    def test_full_sequence_determinism(self) -> None: ...


class TestInfoDelay:
    def test_near_event_same_turn(self) -> None: ...
    def test_far_event_delayed(self) -> None: ...
    def test_at_capital_immediate(self) -> None: ...
    def test_independent_delays(self) -> None: ...
    def test_ledger_window_retain(self) -> None: ...
    def test_no_delivery_during_capital_flight(self) -> None: ...
    def test_capital_move_changes_dist(self) -> None: ...
    def test_event_kind_fields(self) -> None: ...
    def test_faction_specific_visibility(self) -> None: ...


class TestOrderLag:
    def test_travel_time(self) -> None: ...
    def test_same_turn_if_close(self) -> None: ...
    def test_fifo_per_entity(self) -> None: ...
    def test_dead_letter_army_death(self) -> None: ...
    def test_dead_letter_army_consumed(self) -> None: ...
    def test_dead_letter_town_death(self) -> None: ...
    def test_standing_order_persists(self) -> None: ...
    def test_train_standing_repeats(self) -> None: ...
    def test_messenger_pursuit(self) -> None: ...
    def test_fifo_across_movement(self) -> None: ...
    def test_move_capital_instant(self) -> None: ...


class TestCommands:
    def test_move_to_sets_course(self) -> None: ...
    def test_move_to_distance_check(self) -> None: ...
    def test_move_to_from_validation(self) -> None: ...
    def test_move_to_replaces(self) -> None: ...
    def test_move_to_ownership_fail(self) -> None: ...
    def test_build_empty_ground(self) -> None: ...
    def test_build_on_own_town(self) -> None: ...
    def test_build_on_enemy_town(self) -> None: ...
    def test_build_distance_fail(self) -> None: ...
    def test_build_ownership_army(self) -> None: ...
    def test_build_consumes(self) -> None: ...
    def test_move_capital_instant_cmd(self) -> None: ...
    def test_move_capital_guard(self) -> None: ...
    def test_move_capital_guard_speed(self) -> None: ...
    def test_move_capital_blind(self) -> None: ...
    def test_move_capital_insufficient_pop(self) -> None: ...
    def test_move_capital_founds(self) -> None: ...
    def test_old_capital_demoted(self) -> None: ...
    def test_multiple_move_capital_queued(self) -> None: ...
    def test_invalid_commands_ignored(self) -> None: ...
    def test_multiple_commands_per_turn(self) -> None: ...
