"""Tests for engine/combat — weakness-based death resolution."""

from __future__ import annotations


class TestCombat:
    def test_1v1_mutual(self) -> None: ...
    def test_2v1(self) -> None: ...
    def test_3v2(self) -> None: ...
    def test_weakness_counts(self) -> None: ...
    def test_no_enemies_safe(self) -> None: ...
    def test_simultaneous_snapshot(self) -> None: ...
    def test_allies_counted(self) -> None: ...
    def test_multifaction_all_enemies(self) -> None: ...
    def test_mixed_distances(self) -> None: ...
    def test_exactly_at_radius(self) -> None: ...
    def test_just_outside_radius(self) -> None: ...
    def test_3_factions_circle(self) -> None: ...
    def test_2v2_annihilate(self) -> None: ...
    def test_combat_uses_final_positions(self) -> None: ...
