"""Tests for engine/economy — logistic growth, crowding, TRAIN, BUILD."""

from __future__ import annotations


class TestLogisticGrowth:
    def test_village_isolated(self) -> None: ...
    def test_city_at_peak(self) -> None: ...
    def test_at_cap(self) -> None: ...
    def test_over_cap(self) -> None: ...
    def test_annualised_village(self) -> None: ...
    def test_annualised_city(self) -> None: ...
    def test_per_turn_formula(self) -> None: ...
    def test_logistic_peak_location(self) -> None: ...


class TestCrowding:
    def test_two_villages_at_d_eq(self) -> None: ...
    def test_two_markets_at_d_eq(self) -> None: ...
    def test_two_cities_at_d_eq(self) -> None: ...
    def test_closer_than_d_eq(self) -> None: ...
    def test_farther_than_d_eq(self) -> None: ...
    def test_village_near_city(self) -> None: ...
    def test_city_near_village(self) -> None: ...
    def test_cross_size_at_d_eq(self) -> None: ...
    def test_market_provincial_d_eq(self) -> None: ...
    def test_asymmetry_direction(self) -> None: ...
    def test_asymmetry_log_scale(self) -> None: ...
    def test_symmetric_asym(self) -> None: ...
    def test_asymmetry_numeric(self) -> None: ...
    def test_d_eq_uses_min(self) -> None: ...
    def test_two_neighbours_sum(self) -> None: ...
    def test_mixed_near_far(self) -> None: ...
    def test_no_neighbours(self) -> None: ...
    def test_cutoff_at_info_speed(self) -> None: ...
    def test_just_inside_cutoff(self) -> None: ...
    def test_flat_gamma_long_range(self) -> None: ...
    def test_cannot_skip_distant_pairs(self) -> None: ...
    def test_three_body_sum(self) -> None: ...


class TestEconomyCommands:
    def test_town_dies_at_499(self) -> None: ...
    def test_town_survives_at_500(self) -> None: ...
    def test_isolated_never_dies(self) -> None: ...
    def test_build_empty_ground(self) -> None: ...
    def test_build_on_town(self) -> None: ...
    def test_build_consumes_army(self) -> None: ...
    def test_build_distance_fail(self) -> None: ...
    def test_train_reduces_pop(self) -> None: ...
    def test_train_spawns_at_town(self) -> None: ...
    def test_train_insufficient_pop(self) -> None: ...
    def test_train_standing_order(self) -> None: ...
    def test_train_ownership_check(self) -> None: ...
    def test_build_new_town_faction(self) -> None: ...
