"""Tests for engine/config — defaults, overrides, field names."""

from __future__ import annotations


class TestConfig:
    def test_default_values(self) -> None: ...
    def test_config_overrides(self) -> None: ...
    def test_field_names_match_plan(self) -> None: ...
    def test_no_num_factions(self) -> None: ...
    def test_map_field_is_csv(self) -> None: ...
